language: php
php:
  - 7.2
  - 7.3

before_install: phpenv config-add bfreplconfig.ini

before_script:
  - composer install

script: vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)