language: php

php:
  - 7.4
  - 'nightly'

before_script:
  - composer install
  - if [[ $TRAVIS_PHP_VERSION = "7.4" ]]; then echo yes | pecl install apcu 5.1.18; fi
  - echo $'apc.enabled=1\napc.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
