#!/usr/bin/env php
<?php

/**
 * REPL executable file
 * 
 * @package bingo-functional-repl
 * @author Lochemem Bruno Michael
 * @license Apache 2.0
 */

foreach (
    [
        __DIR__ . '/../autoload.php',
        __DIR__ . '/../../autoload.php',
        __DIR__ . '/../vendor/autoload.php',
        __DIR__ . '/vendor/autoload.php',
        __DIR__ . '/../../vendor/autoload.php'
    ] as $file
) {
    if (file_exists($file)) {
        define('AUTOLOAD_PHP_FILE', $file);
        break;
    }    
}

if (!defined('AUTOLOAD_PHP_FILE')) {
     fwrite(STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    die(1);
}

require AUTOLOAD_PHP_FILE;

use Chemem\Bingo\Functional\Repl\{IO as Impure, Constants};
use Chemem\Bingo\Functional\Algorithms as A;
use Chemem\Bingo\Functional\Functors\Monads\IO;

/**
 * REPL exception handler
 * 
 * @param callable $exceptionHandlerFunction
 */

set_exception_handler(
    static function ($exception) {
        echo A\concat(
            ' ',
            Constants\REPL_EXCEPTION, 
            $exception->getMessage()
        );
        return false;
    }
);

/**
 * REPL function error handler
 * 
 * @param callable $errorHandlerFunction
 */

set_error_handler(
    function ($errNo, $errStr) {
        echo A\concat(' ', Constants\REPL_ERROR, $errNo, $errStr, '');
    }
);

/**
 * main function
 * 
 * @return object IO
 */

function main() : IO
{
    return Impure\getInput()
        ->bind(Impure\transformInput)
        ->map(Impure\printOutput);
}

/**
 * execute function
 * 
 * @return void 
 */

function execute() : void
{
    printf('%s', A\concat(PHP_EOL, Constants\REPL_WELCOME, ''));
    while (true) {
        main()
            ->bind(
                A\partialLeft(
                    A\curryN(2, 'printf'),
                    '%s'
                )
            )
            ->exec();
    }
}

execute();
